
services:
  # Radarr - https://hotio.dev/containers/sonarr/
  sonarr:
    container_name: sonarr 
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped    
    pull_policy: always
    # Port will be proxied, so no need to expose it here
    # ports:
    #   - 8989:8989 
    env_file: .env
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${ENTERTAINMENT_DIR}:/data
    networks:
      - frontend-swarm
    labels:
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.rlgland.site`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=cloudflare"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

networks:
  frontend-swarm:
    external: true