
services:
  # Radarr - https://hotio.dev/containers/prowlarr/
  prowlarr :
    container_name: prowlarr 
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped    
    pull_policy: always
    # Port will be proxied, so no need to expose it here
    # ports:
    #   - 9696:9696 
    env_file: .env
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    networks:
      - frontend-swarm
    labels:
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.rlgland.site`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certresolver=cloudflare"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

networks:
  frontend-swarm:
    external: true