version: '3.7'

services:
  # Radarr - https://hotio.dev/containers/prowlarr/
  prowlarr :
    container_name: prowlarr 
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped    
    pull_policy: always
    ports:
      - 9696:9696 
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ./prowlarr:/config
