
services:
  # Radarr - https://hotio.dev/containers/radarr/
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped    
    pull_policy: always
    # Port will be proxied, so no need to expose it here
    # ports:
    #   - 7878:7878
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/radarr:/config
      - ${ENTERTAINMENT_DIR}:/data
    networks:
      - frontend-swarm
    labels:
      - "traefik.http.routers.radarr.rule=Host(`radarr.rlgland.site`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

networks:
  frontend-swarm:
    external: true